publish:
  docker:
    username: $$DOCKER_USERNAME
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    registry: registry.aliyuncs.com
    repo: xiaolu-img/xiaolusys-ui
    tag: latest
    file: Dockerfile
    mirror: https://n5fb0zgg.mirror.aliyuncs.com
    when:
      branch: [staging,master]
deploy:
  ssh:
    host: 
      - staging.xiaolumm.com
    when:
      branch: staging
    user: root
    commands:
      - docker pull registry.aliyuncs.com/xiaolu-img/xiaolusys-ui
      - docker run --rm --volumes-from=static registry.aliyuncs.com/xiaolu-img/xiaolusys-ui cp -rf static /data/site_media
  ssh:
    host: 
      - staging.xiaolumm.com
      - sale.xiaolumm.com
    when:
      branch: master
    user: root
    commands:
      - docker pull registry.aliyuncs.com/xiaolu-img/xiaolusys-ui
      - docker run --rm --volumes-from=static registry.aliyuncs.com/xiaolu-img/xiaolusys-ui cp -rf static /data/site_media
  ssh:
    host: 
      - euho.xiaolumm.com
    when:
      branch: euho
    user: root
    commands:
      - docker pull registry.aliyuncs.com/xiaolu-img/xiaolusys-ui
      - docker run --rm --volumes-from=static registry.aliyuncs.com/xiaolu-img/xiaolusys-ui cp -rf static /data/site_media