publish:
  docker:
    username: $$DOCKER_USERNAME
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    registry: registry.aliyuncs.com
    repo: ndpuz-img/ndpuzsys-ui
    tag: latest
    file: Dockerfile
    mirror: https://kpm1lqaf.mirror.aliyuncs.com
    when:
      branch: [staging,master]
